Drop mem 😟
sindresorhus/os-locale pull request #47
Opened 2021-03-08 08:15 UTC by fregante

I know this is probably not something welcome, but with just one option maybe it's not necessary here. Together with #46 it'd reduce `os-locale`’s dependencies from 26 to 2.

<img width="1117" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/110292037-41379500-7fb2-11eb-8035-0ecb7d2c45eb.png">

2021-03-08 09:32 UTC, sindresorhus requested changes

2021-03-08 09:32 UTC, sindresorhus commented on index.js
> +const asyncCache = {};
Can you use a `Map`?

2021-03-09 05:14 UTC, merged

2021-03-09 05:15 UTC, fregante commented
I preferred the previous title 😟 😁

2021-03-10 09:46 UTC, fregante commented
I was thinking… does spawn change the value here? Doesn’t it just change the way the value is gotten?

2021-03-10 10:00 UTC, sindresorhus commented
Yes, the result can be different. The `{spawn: false}` case has less chance of finding the locale (see the docs).

2021-03-10 10:07 UTC, fregante commented
What about sync/async? There could be just one map